Repository AY2425S1-CS2103T-T13-3/tp, pull requests merged in 2024-11, with the labels that each got.

#151 add in placeholders for the lists
  src/main/java/seedu/address/ui/CombinedListPanel.java
  src/main/java/seedu/address/ui/OwnerListPanel.java
  src/main/java/seedu/address/ui/PetListPanel.java
Labels: priority.High, alpha-bug

#153 remove the need for list both and to only use list
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PawPatrolParserTest.java
Labels: alpha-bug

#174 update example commands in ug
  docs/UserGuide.md
Labels: priority.High

#176 Cap Warnings
  src/main/java/seedu/address/model/owner/LinkedPetList.java
  src/main/java/seedu/address/model/pet/LinkedOwnerList.java
Labels: alpha-bug

#186 Remove Person reference from DG
  docs/DeveloperGuide.md
Labels: alpha-bug

#263 Fix delete pet use case
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium, severity.Low, type.DeveloperGuide

#272 Update Model Class Diagram in DG
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagramUpdated.png
Labels: type.Bug, priority.Medium, severity.VeryLow, type.DeveloperGuide
